// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOl6bqIxuS6HZ1v7qDWkPoo3pixNa752s',
    appId: '1:793788851035:web:3927d19b021a6706f8f07e',
    messagingSenderId: '793788851035',
    projectId: 'focus-fighters',
    authDomain: 'focus-fighters.firebaseapp.com',
    storageBucket: 'focus-fighters.appspot.com',
    measurementId: 'G-GVR955KPHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMRywyMXtiHECqGkcbY43G5x8YYdQo_GA',
    appId: '1:793788851035:android:e0d1392152587417f8f07e',
    messagingSenderId: '793788851035',
    projectId: 'focus-fighters',
    storageBucket: 'focus-fighters.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjsBohMlOm0kufWbjSvObJkRNHZiPVfm0',
    appId: '1:793788851035:ios:09244df8799505c9f8f07e',
    messagingSenderId: '793788851035',
    projectId: 'focus-fighters',
    storageBucket: 'focus-fighters.appspot.com',
    iosBundleId: 'com.example.basic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjsBohMlOm0kufWbjSvObJkRNHZiPVfm0',
    appId: '1:793788851035:ios:74c4a5a5fd92b516f8f07e',
    messagingSenderId: '793788851035',
    projectId: 'focus-fighters',
    storageBucket: 'focus-fighters.appspot.com',
    iosBundleId: 'com.example.basic.RunnerTests',
  );
}
